name: Scheduled and Push API Post

on:
  schedule:
    - cron: "0 6,13,16,20 * * *" # At 6 AM, 1 PM, 4 PM, and 8 PM UTC
  push:
    branches:
      - main

jobs:
  post_to_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run posting script
        run: deno run --allow-net --allow-env scripts/post-greeting.ts
        env:
          API_KEY: ${{ secrets.API_KEY }}
