name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: replix-394315
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: docker compose -f docker-compose.yml build

      - name: Tag Docker image
        run: docker tag deno-image us-central1-docker.pkg.dev/replix-394315/deno-repository/deno-cloudrun-image:${{ github.sha }}

      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/replix-394315/deno-repository/deno-cloudrun-image:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: deno-service
          image: us-central1-docker.pkg.dev/replix-394315/deno-repository/deno-cloudrun-image:${{ github.sha }}
          region: us-central1
          env_vars: |
            ENV=PRODUCTION

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
