name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker compose -f docker-compose.yml build \
            --build-arg GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} \
            --build-arg GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} \
            --build-arg REDIRECT_URI=${{ vars.REDIRECT_URI }}

      - name: Tag Docker image
        run: docker tag deno-image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image:${{ github.sha }}

      - name: Push Docker image
        run: docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: deno-service
          image: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image:${{ github.sha }}
          region: ${{ vars.GCP_REGION }}
          env_vars: |
            ENV=PRODUCTION
            DENO_KV_PATH=/app/db/sqlite.db
            GCS_BUCKET=${{ vars.GCS_BUCKET }}
            GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}
            GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }}
            REDIRECT_URI=${{ vars.REDIRECT_URI }}
          flags: --allow-unauthenticated --memory=1Gi

      - name: Debug Environment Variables
        run: |
          echo "GCS_BUCKET value exists: ${{ vars.GCS_BUCKET != '' }}"
          echo "GH_CLIENT_ID secret exists: ${{ secrets.GH_CLIENT_ID != '' }}"
          echo "GH_CLIENT_SECRET secret exists: ${{ secrets.GH_CLIENT_SECRET != '' }}"
          echo "REDIRECT_URI value exists: ${{ vars.REDIRECT_URI != '' }}"

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: generate public files
        run: deno task public_build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ vars.GCP_PROJECT_ID || 'replix-394315' }}
        run: |
          # Create .firebaserc file dynamically
          echo '{
            "projects": {
              "default": "'$FIREBASE_PROJECT'"
            }
          }' > .firebaserc

          # Create firebase.json file dynamically with custom domain, redirects, and CORS headers
          echo '{
            "hosting": {
              "public": "public",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ],
              "headers": [
                {
                  "source": "/api/**",
                  "headers": [
                    { "key": "Access-Control-Allow-Origin", "value": "https://social.fastro.dev" },
                    { "key": "Access-Control-Allow-Methods", "value": "GET, POST, OPTIONS, DELETE, PUT" },
                    { "key": "Access-Control-Allow-Headers", "value": "Content-Type, Authorization" },
                    { "key": "Access-Control-Max-Age", "value": "86400" }
                  ]
                }
              ],
              "redirects": [
                {
                  "source": "/post/:postId*",
                  "destination": "https://web.fastro.dev/post/:postId",
                  "type": 301
                },
                {
                  "source": "/auth/callback",
                  "destination": "https://web.fastro.dev/auth/callback",
                  "type": 301
                }
              ],
              "rewrites": [
                {
                  "source": "**",
                  "destination": "/index.html"
                }
              ],
              "appAssociation": "AUTO",
              "cleanUrls": true
            }
          }' > firebase.json

          # Now deploy to Firebase hosting
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"

      - name: Show generated firebase.json
        run: cat firebase.json

      - name: Show generated .firebaserc
        run: cat .firebaserc

      - name: Clean up old images
        if: success()
        run: |
          # Current image SHA
          CURRENT_SHA=${{ github.sha }}
          echo "Current image SHA: $CURRENT_SHA"

          # Ensure we have proper permissions
          gcloud config set artifacts/location ${{ vars.GCP_REGION }}

          # List all tags with version creation time
          echo "Listing all available images:"
          gcloud artifacts docker tags list ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image \
            --sort-by=~CREATE_TIME \
            --format="table[box](tag, create_time)"

          # Keep current image and delete older ones
          echo "Finding tags to delete..."
          OLD_TAGS=$(gcloud artifacts docker tags list ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image \
            --format="value(tag)" | grep -v "^${CURRENT_SHA}$" || echo "")

          if [ -z "$OLD_TAGS" ]; then
            echo "No old tags found to delete"
          else
            for TAG in $OLD_TAGS; do
              echo "Deleting image with tag: $TAG"
              gcloud artifacts docker tags delete ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image:$TAG --quiet || echo "Failed to delete tag $TAG"
            done
          fi

          echo "Running garbage collection to clean up untagged images"
          gcloud artifacts docker images list ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image \
            --filter="NOT tags:*" --format="value(version)" | while read -r DIGEST; do
            echo "Deleting untagged image: $DIGEST"
            gcloud artifacts docker images delete ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image@$DIGEST --quiet || echo "Failed to delete untagged image $DIGEST"
          done
