name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker compose -f docker-compose.yml build \
            --build-arg GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} \
            --build-arg GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} \
            --build-arg REDIRECT_URI=${{ vars.REDIRECT_URI }}

      - name: Tag Docker image
        run: docker tag deno-image ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image:${{ github.sha }}

      - name: Push Docker image
        run: docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image:${{ github.sha }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: deno-service
          image: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image:${{ github.sha }}
          region: ${{ vars.GCP_REGION }}
          env_vars: |
            ENV=PRODUCTION
            DENO_KV_PATH=/app/db/sqlite.db
            GCS_BUCKET=${{ vars.GCS_BUCKET }}
            GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}
            GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }}
            REDIRECT_URI=${{ vars.REDIRECT_URI }}
          flags: --allow-unauthenticated --memory=1Gi

      - name: Debug Environment Variables
        run: |
          echo "GCS_BUCKET value exists: ${{ vars.GCS_BUCKET != '' }}"
          echo "GH_CLIENT_ID secret exists: ${{ secrets.GH_CLIENT_ID != '' }}"
          echo "GH_CLIENT_SECRET secret exists: ${{ secrets.GH_CLIENT_SECRET != '' }}"
          echo "REDIRECT_URI value exists: ${{ vars.REDIRECT_URI != '' }}"

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ vars.GCP_PROJECT_ID || 'replix-394315' }}
        run: |
          # Create .firebaserc file dynamically
          echo '{
            "projects": {
              "default": "'$FIREBASE_PROJECT'"
            }
          }' > .firebaserc

          # Create firebase.json file dynamically with custom domain and redirects
          echo '{
            "hosting": {
              "public": "public",
              "ignore": [
                "firebase.json",
                "**/.*",
                "**/node_modules/**"
              ],
              "redirects": [
                {
                  "source": "/post/:postId*",
                  "destination": "https://web.fastro.dev/post/:postId",
                  "type": 301
                }
              ],
              "rewrites": [
                {
                  "source": "**",
                  "destination": "/index.html"
                }
              ],
              "appAssociation": "AUTO",
              "cleanUrls": true
            }
          }' > firebase.json

          # Now deploy to Firebase hosting
          firebase deploy --only hosting --token "$FIREBASE_TOKEN"

      - name: Clean up old images
        if: success()
        run: |
          # Current image SHA
          CURRENT_SHA=${{ github.sha }}
          echo "Current image SHA: $CURRENT_SHA"

          # Set appropriate timeout for gcloud commands
          gcloud config set artifacts/location ${{ vars.GCP_REGION }}

          # Check service account permissions
          echo "Checking permissions:"
          gcloud artifacts repositories get-iam-policy deno-repository \
            --location=${{ vars.GCP_REGION }} \
            --format="yaml" || echo "Permission check failed, but continuing"

          # List all images with detailed output for debugging
          echo "Listing all available images:"
          gcloud artifacts docker images list ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image \
            --format="table[box](uri,createTime,tags)"

          # List and delete old tags - more explicit approach
          echo "Finding images to delete (keeping 5 most recent):"
          OLD_IMAGES=$(gcloud artifacts docker images list ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image \
            --sort-by=~createTime \
            --limit=999 \
            --format="value(uri)" | tail -n +6)

          if [ -z "$OLD_IMAGES" ]; then
            echo "No old images to delete or fewer than 6 images found"
          else
            echo "Found $(echo "$OLD_IMAGES" | wc -l) image(s) to delete"
            echo "$OLD_IMAGES" | while read -r IMAGE_URI; do
              echo "Deleting image: $IMAGE_URI"
              gcloud artifacts docker images delete "$IMAGE_URI" --delete-tags --async --quiet || echo "Failed to delete $IMAGE_URI"
            done
          fi

          # Explicitly exclude the current image from deletion
          echo "Cleaning up any remaining untagged images (except current):"
          UNTAGGED_IMAGES=$(gcloud artifacts docker images list ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/deno-repository/deno-cloudrun-image \
            --filter="NOT tags:* AND NOT tags:$CURRENT_SHA" \
            --format="value(uri)")

          if [ -n "$UNTAGGED_IMAGES" ]; then
            echo "$UNTAGGED_IMAGES" | while read -r IMAGE_URI; do
              echo "Deleting untagged image: $IMAGE_URI"
              gcloud artifacts docker images delete "$IMAGE_URI" --async --quiet || echo "Failed to delete $IMAGE_URI"
            done
          else
            echo "No untagged images found for deletion"
          fi
